// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcktetabnmkupvmobsyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhja3RldGFibm1rdXB2bW9ic3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1MzU2NDIsImV4cCI6MjA4OTExMTY0Mn0.8wn04csnqPKQ1uf7G9ucZ8mtQTtSXutDjV6qJr6WkXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});